# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build ATL
      run: dotnet build ATL --no-restore
    - name: Build ATL.test
      run: dotnet build ATL.test --no-restore
    - name: Test
      run: dotnet test ATL.test --no-build --verbosity normal
    - name: Coverlet coverage test
      uses: b3b00/coverlet-action@1.2.5
      with:
        testProject: 'ATL.test/ATL.test.csproj'
        output: 'lcov.info'
        outputFormat: 'opencover'
        excludes: '[program]*,[test]test.*'
        threshold: 80
    - name: SonarCloud
      uses: highbyte/sonarscan-dotnet@v2.2.2
      with:
        # The key of the SonarQube project
        sonarProjectKey: Zeugma440_atldotnet
        # The name of the SonarQube project
        sonarProjectName:  atldotnet
        # The name of the SonarQube organization in SonarCloud. For hosted SonarQube, skip this setting.
        sonarOrganization: zeugma440-github
        # Optional command arguments to dotnet test
        dotnetTestArguments: --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
        # Optional extra command arguments the the SonarScanner 'begin' command
        sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: CodeCov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: /TestResults/**/coverage.opencover.xml # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
